name: Publish to Sonatype Central

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  JAVA_VERSION: 11

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Cache SBT
      uses: actions/cache@v4
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/**') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Import GPG key
      run: |
        echo "${{ secrets.PGP_SECRET }}" | base64 --decode | gpg --batch --import
        gpg --list-keys

    - name: Publish to Sonatype Central (Scala 2.12)
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
      run: |
        sbt "++2.12.19" clean publishSigned sonatypeBundleRelease

    - name: Publish to Sonatype Central (Scala 2.13)
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
      run: |
        sbt "++2.13.16" clean publishSigned sonatypeBundleRelease

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
